### ISSUE TITLE
Question about BEV voxelization

### ISSUE THREAD

**Issue by gujiaqivadin** [wangguojun2018/MVAF-Net#2]
Hello, wangguojun!
       Thanks for your excellent work. I am a little confused about BEV voxelization. In mmdet3d code, the voxel_layer (hard voxel and others) is not differentiable in implementation. Thus, the weights of prior stages will not be updated. I wonder how you transfer it to a differentiable module, did you rewrite the voxel_layer by yourself? This module input point_features and output bev_features, right? And I am also looking forward to see your code soon.

**Comment by wangguojun2018** [comment]
We use dynamic scatter in mmdetection3d


 
---Original---

**Comment by gujiaqivadin** [comment]
Can you tell me the input and the output of dynamic scatter. I also read its code, but found the input of dynamic scatter is (points,coors). Points is our point-wise features in Network, but what is the coors means? voxel_coors or point_coors?

**Comment by gujiaqivadin** [comment]
> Can you tell me the input and the output of dynamic scatter. I also read its code, but found the input of dynamic scatter is (points,coors). Points is our point-wise features in Network, but what is the coors means? voxel_coors or point_coors?

As I find that coors neet to be type Int, it may be voxel_coors?
